version: '3.8'

services:
  chroma:
    container_name: chroma
    build:
      context: https://github.com/chroma-core/chroma.git
    ports:
      - "6666:8000"
    volumes:
      - ./chroma_/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE

  mariadb:
    image: mariadb
    container_name: mariadb
    ports:
      - "6667:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=acce
    volumes:
      - ./maria_/var/lib/mysql
    restart: always
