services:
  chroma:
    image: chromadb/chroma:latest
    container_name: chroma
    ports:
      - "6666:8000"
    volumes:
      - /Users/a08418/Documents/CoE/db/chroma:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE

  mariadb:
    image: mariadb
    container_name: mariadb
    ports:
      - "6667:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=acce
    volumes:
      - /Users/a08418/Documents/CoE/db/maria:/var/lib/mysql
    restart: always

  kosentencebert:
    build:
      context: ./kosentencebert
      dockerfile: Dockerfile
    container_name: kosentencebert
    ports:
      - "6668:8080"
    volumes:
      - /Users/a08418/Documents/CoE/db/kosentencebert:/app/data
    restart: always
    environment:
      - PYTHONPATH=/app
