services:
  coe-backend:
    env_file:
      - ./CoE-Backend/.env.dev
    environment:
      - APP_ENV=development
      - DEBUG=true
      - LOG_LEVEL=DEBUG
      - RELOAD=false
      - RUN_MIGRATIONS=true
      - RAG_PIPELINE_URL=http://coe-ragpipeline:8001
      # Use infra from prod stack via host gateway
      - DB_HOST=host.docker.internal
      - DB_PORT=6667
      - CHROMA_HOST=host.docker.internal
      - CHROMA_PORT=6666
      - REDIS_HOST=host.docker.internal
      - REDIS_PORT=6669
    ports:
      - "127.0.0.1:8002:8000"   # expose only to host for prod nginx proxy
    extra_hosts:
      - "host.docker.internal:host-gateway"

  coe-ragpipeline:
    env_file:
      - ./CoE-RagPipeline/.env.dev
    environment:
      - APP_ENV=development
      - DEBUG=true
      - LOG_LEVEL=DEBUG
      - RELOAD=false
      - RUN_MIGRATIONS=true
      # Use infra from prod stack via host gateway
      - DB_HOST=host.docker.internal
      - DB_PORT=6667
      - CHROMA_HOST=host.docker.internal
      - CHROMA_PORT=6666
      - REDIS_HOST=host.docker.internal
      - REDIS_PORT=6669
    ports:
      - "127.0.0.1:8003:8001"   # expose only to host for prod nginx proxy
    extra_hosts:
      - "host.docker.internal:host-gateway"
