name: coe-prod-full

networks:
  coe-prod-net:
    driver: bridge

volumes:
  prod-maria-data:
  prod-chroma-data:
  prod-redis-data:

services:
  chroma-prod:
    image: chromadb/chroma:latest
    container_name: chroma-prod
    networks: [coe-prod-net]
    volumes:
      - prod-chroma-data:/data

  mariadb-prod:
    image: mariadb:latest
    container_name: mariadb-prod
    environment:
      - MARIADB_ROOT_PASSWORD=acce
      - MARIADB_DATABASE=coe_db
      - MARIADB_USER=coe_user
      - MARIADB_PASSWORD=coe_password
    volumes:
      - prod-maria-data:/var/lib/mysql
    networks: [coe-prod-net]

  redis-prod:
    image: redis:7-alpine
    container_name: redis-prod
    command: redis-server --appendonly yes --requirepass coe_redis_password
    volumes:
      - prod-redis-data:/data
    networks: [coe-prod-net]

  coe-backend:
    build:
      context: ./CoE-Backend
      dockerfile: Dockerfile
    container_name: coe-backend-prod
    env_file:
      - ./CoE-Backend/.env.prod
    environment:
      - TZ=Asia/Seoul
      - RUN_MIGRATIONS=true
      - DB_HOST=mariadb-prod
      - DB_PORT=3306
      - CHROMA_HOST=chroma-prod
      - CHROMA_PORT=8000
      - REDIS_HOST=redis-prod
      - REDIS_PORT=6379
      - APP_ENV=production
      - DEBUG=false
      - LOG_LEVEL=INFO
      - RELOAD=false
      - PYTHONUNBUFFERED=1
      - LOG_TO_FILE=true
      - RAG_PIPELINE_URL=http://coe-ragpipeline-prod:8001
    depends_on:
      - chroma-prod
      - mariadb-prod
      - redis-prod
      - coe-ragpipeline
    ports:
      - "18000:8000"
    networks: [coe-prod-net]

  coe-ragpipeline:
    build:
      context: ./CoE-RagPipeline
      dockerfile: Dockerfile
    container_name: coe-ragpipeline-prod
    env_file:
      - ./CoE-RagPipeline/.env.prod
    environment:
      - TZ=Asia/Seoul
      - RUN_MIGRATIONS=true
      - DB_HOST=mariadb-prod
      - DB_PORT=3306
      - CHROMA_HOST=chroma-prod
      - CHROMA_PORT=8000
      - REDIS_HOST=redis-prod
      - REDIS_PORT=6379
      - APP_ENV=production
      - DEBUG=false
      - LOG_LEVEL=INFO
      - RELOAD=false
    depends_on:
      - chroma-prod
      - mariadb-prod
      - redis-prod
    ports:
      - "18001:8001"
    networks: [coe-prod-net]
