services:
  chroma:
    image: chromadb/chroma:latest
    container_name: chroma
    ports:
      - "6666:8000"
    volumes:
      - /Users/a08418/Documents/CoE/db/chroma:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE

  mariadb:
    image: mariadb
    container_name: mariadb
    ports:
      - "6667:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=acce
    volumes:
      - /Users/a08418/Documents/CoE/db/maria:/var/lib/mysql
    restart: always

  koEmbeddings:
    image: ghcr.io/huggingface/text-embeddings-inference:cpu-latest
    container_name: koEmbeddings
    ports:
      - "6668:80"
    volumes:
      - /Users/a08418/Documents/CoE/db/koEmbeddings:/data
    restart: always
    command: --model-id upskyy/e5-large-korean --port 80
