services:
  coe-backend:
    env_file:
      - ./CoE-Backend/.env.prod
    environment:
      - APP_ENV=production
      - DEBUG=false
      - LOG_LEVEL=INFO
      - RELOAD=false
      - RUN_MIGRATIONS=true
      - RAG_PIPELINE_URL=http://host.docker.internal:18001
      - DB_HOST=host.docker.internal
      - DB_PORT=6667
      - CHROMA_HOST=host.docker.internal
      - CHROMA_PORT=6666
      - REDIS_HOST=host.docker.internal
      - REDIS_PORT=6669
    ports:
      - "127.0.0.1:18000:8000"  # prod backend exposed only to host
    extra_hosts:
      - "host.docker.internal:host-gateway"

  coe-ragpipeline:
    env_file:
      - ./CoE-RagPipeline/.env.prod
    environment:
      - APP_ENV=production
      - DEBUG=false
      - LOG_LEVEL=INFO
      - RELOAD=false
      - RUN_MIGRATIONS=true
      - DB_HOST=host.docker.internal
      - DB_PORT=6667
      - CHROMA_HOST=host.docker.internal
      - CHROMA_PORT=6666
      - REDIS_HOST=host.docker.internal
      - REDIS_PORT=6669
    ports:
      - "127.0.0.1:18001:8001"  # prod rag exposed only to host
    extra_hosts:
      - "host.docker.internal:host-gateway"

