name: coe-prod

networks:
  coe-prod-net:
    name: coe-prod-net
    driver: bridge

services:
  chroma:
    image: chromadb/chroma:latest
    volumes:
      - /home/greatjlim/projects/db/prod/chroma:/data
    networks: [coe-prod-net]

  chroma-external:
    image: chromadb/chroma:latest
    profiles: ["external-demo"]
    ports:
      - "6670:8000"
    volumes:
      - /home/greatjlim/projects/db/prod/chroma_external:/data
    networks: [coe-prod-net]

  mariadb:
    image: mariadb:latest
    environment:
      - MARIADB_ROOT_PASSWORD=acce
      - MARIADB_DATABASE=coe_db
      - MARIADB_USER=coe_user
      - MARIADB_PASSWORD=coe_password
    volumes:
      - /home/greatjlim/projects/db/prod/mariadb:/var/lib/mysql
    networks: [coe-prod-net]
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping -h 127.0.0.1 -uroot -pacce --silent || exit 1"]
      interval: 2s
      timeout: 5s
      retries: 120
      start_period: 15s

  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes --requirepass coe_redis_password
    volumes:
      - /home/greatjlim/projects/db/prod/redis:/data
    networks: [coe-prod-net]

  backend:
    build:
      context: ./CoE-Backend
      dockerfile: Dockerfile
    env_file:
      - ./CoE-Backend/.env.prod
    environment:
      - TZ=Asia/Seoul
      - RUN_MIGRATIONS=true
      - DB_HOST=mariadb
      - DB_PORT=3306
      - CHROMA_HOST=chroma
      - CHROMA_PORT=8000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - APP_ENV=production
      - DEBUG=false
      - LOG_LEVEL=INFO
      - RELOAD=false
      - PYTHONUNBUFFERED=1
      - LOG_TO_FILE=true
      - LOG_DIR=/app/logs
      - RAG_PIPELINE_URL=http://ragpipeline:8001
    depends_on:
      mariadb:
        condition: service_healthy
      chroma:
        condition: service_started
      redis:
        condition: service_started
      ragpipeline:
        condition: service_started
    ports:
      - "18000:8000"
    volumes:
      - /home/greatjlim/projects/logs/coe-backend/prod:/app/logs
    networks: [coe-prod-net]

  ragpipeline:
    build:
      context: ./CoE-RagPipeline
      dockerfile: Dockerfile
    env_file:
      - ./CoE-RagPipeline/.env.prod
    environment:
      - TZ=Asia/Seoul
      - ROOT_PATH=/rag
      - RUN_MIGRATIONS=true
      - DB_HOST=mariadb
      - DB_PORT=3306
      - CHROMA_HOST=chroma
      - CHROMA_PORT=8000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - APP_ENV=production
      - DEBUG=false
      - LOG_LEVEL=INFO
      - RELOAD=false
      - LOG_TO_FILE=true
      - LOG_DIR=/app/logs
    depends_on:
      - chroma
      - mariadb
      - redis
    ports:
      - "18001:8001"
    volumes:
      - /home/greatjlim/projects/logs/coe-ragpipeline/prod:/app/logs
    networks: [coe-prod-net]
