services:
  nginx-edge:
    image: nginx:latest
    container_name: nginx-edge
    depends_on:
      - setup-ssl-dummy-edge
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.edge.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certbot/www:/var/www/certbot
      - ./nginx/certbot/conf:/etc/letsencrypt
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: >-
      sh -c "
      CERT_SUM=''; \
      ( while :; do \
          NEW_SUM=$(find /etc/letsencrypt/live -type f -name '*.pem' -exec sha256sum {} + 2>/dev/null | sort | sha256sum || echo 'none'); \
          if [ \"$$NEW_SUM\" != \"$$CERT_SUM\" ]; then \
            if [ -n \"$$CERT_SUM\" ]; then echo '[nginx-edge] certs changed, reloading...'; nginx -s reload; fi; \
            CERT_SUM=\"$$NEW_SUM\"; \
          fi; \
          sleep 30; \
        done ) & \
      nginx -g 'daemon off;'"

  # Optional: enable after cutover to 80/443 for real certificates
  certbot-edge:
    image: certbot/certbot:latest
    container_name: certbot-edge
    depends_on:
      - nginx-edge
    volumes:
      - ./nginx/certbot/www:/var/www/certbot
      - ./nginx/certbot/conf:/etc/letsencrypt
    entrypoint: ["/bin/sh","-c"]
    command: |
      set -e
      trap 'exit 0' TERM INT
      echo 'Waiting for nginx-edge to serve ACME challenge...'
      sleep 5
      certbot certonly --non-interactive --agree-tos \
        --register-unsafely-without-email \
        --webroot -w /var/www/certbot \
        -d greatcoe.cafe24.com \
        -d dev.greatcoe.cafe24.com
      echo 'Certificates issued (edge). Auto-renew service will keep them updated.'
      sleep infinity

  certbot-renew-edge:
    image: certbot/certbot:latest
    container_name: certbot-renew-edge
    restart: always
    depends_on:
      - nginx-edge
    volumes:
      - ./nginx/certbot/www:/var/www/certbot
      - ./nginx/certbot/conf:/etc/letsencrypt
    entrypoint: ["/bin/sh","-c"]
    command: |
      while :; do
        certbot renew --webroot -w /var/www/certbot --quiet --keep-until-expiring
        sleep 12h
      done

  setup-ssl-dummy-edge:
    image: alpine:3
    container_name: setup-ssl-dummy-edge
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
    entrypoint: ["/bin/sh","-c"]
    command: >-
      "set -e; \
      apk add --no-cache openssl >/dev/null; \
      mkdir -p /etc/letsencrypt/live/greatcoe.cafe24.com; \
      if [ ! -f /etc/letsencrypt/live/greatcoe.cafe24.com/fullchain.pem ]; then \
        echo 'Creating temporary self-signed cert for greatcoe.cafe24.com'; \
        openssl req -x509 -nodes -newkey rsa:2048 -days 3 \
          -keyout /etc/letsencrypt/live/greatcoe.cafe24.com/privkey.pem \
          -out /etc/letsencrypt/live/greatcoe.cafe24.com/fullchain.pem \
          -subj "/CN=greatcoe.cafe24.com"; \
      else \
        echo 'Existing prod cert found; skipping self-signed (prod).'; \
      fi; \
      mkdir -p /etc/letsencrypt/live/dev.greatcoe.cafe24.com; \
      if [ ! -f /etc/letsencrypt/live/dev.greatcoe.cafe24.com/fullchain.pem ]; then \
        echo 'Creating temporary self-signed cert for dev.greatcoe.cafe24.com'; \
        openssl req -x509 -nodes -newkey rsa:2048 -days 3 \
          -keyout /etc/letsencrypt/live/dev.greatcoe.cafe24.com/privkey.pem \
          -out /etc/letsencrypt/live/dev.greatcoe.cafe24.com/fullchain.pem \
          -subj "/CN=dev.greatcoe.cafe24.com"; \
      else \
        echo 'Existing dev cert found; skipping self-signed (dev).'; \
      fi; \
      echo 'Done.'; \
      sleep 1"
