name: coe-dev-full

networks:
  coe-dev-net:
    driver: bridge

volumes:
  dev-maria-data:
  dev-chroma-data:
  dev-redis-data:

services:
  chroma-dev:
    image: chromadb/chroma:latest
    container_name: chroma-dev
    networks: [coe-dev-net]
    volumes:
      - dev-chroma-data:/data

  mariadb-dev:
    image: mariadb:latest
    container_name: mariadb-dev
    environment:
      - MARIADB_ROOT_PASSWORD=acce
      - MARIADB_DATABASE=coe_db
      - MARIADB_USER=coe_user
      - MARIADB_PASSWORD=coe_password
    volumes:
      - dev-maria-data:/var/lib/mysql
    networks: [coe-dev-net]

  redis-dev:
    image: redis:7-alpine
    container_name: redis-dev
    command: redis-server --appendonly yes --requirepass coe_redis_password
    volumes:
      - dev-redis-data:/data
    networks: [coe-dev-net]

  coe-backend:
    build:
      context: ./CoE-Backend
      dockerfile: Dockerfile
    container_name: coe-backend-dev
    env_file:
      - ./CoE-Backend/.env.dev
    environment:
      - TZ=Asia/Seoul
      - RUN_MIGRATIONS=true
      - DB_HOST=mariadb-dev
      - DB_PORT=3306
      - CHROMA_HOST=chroma-dev
      - CHROMA_PORT=8000
      - REDIS_HOST=redis-dev
      - REDIS_PORT=6379
      - APP_ENV=development
      - DEBUG=true
      - LOG_LEVEL=DEBUG
      - RELOAD=false
      - PYTHONUNBUFFERED=1
      - LOG_TO_FILE=true
      - RAG_PIPELINE_URL=http://coe-ragpipeline-dev:8001
    depends_on:
      - chroma-dev
      - mariadb-dev
      - redis-dev
      - coe-ragpipeline
    ports:
      - "18002:8000"
    networks: [coe-dev-net]

  coe-ragpipeline:
    build:
      context: ./CoE-RagPipeline
      dockerfile: Dockerfile
    container_name: coe-ragpipeline-dev
    env_file:
      - ./CoE-RagPipeline/.env.dev
    environment:
      - TZ=Asia/Seoul
      - RUN_MIGRATIONS=true
      - DB_HOST=mariadb-dev
      - DB_PORT=3306
      - CHROMA_HOST=chroma-dev
      - CHROMA_PORT=8000
      - REDIS_HOST=redis-dev
      - REDIS_PORT=6379
      - APP_ENV=development
      - DEBUG=true
      - LOG_LEVEL=DEBUG
      - RELOAD=false
    depends_on:
      - chroma-dev
      - mariadb-dev
      - redis-dev
    ports:
      - "18003:8001"
    networks: [coe-dev-net]
